version: "3"
services:

  labs:

    image: 'gitlab/gitlab-ee'
    hostname: 'localhost'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - '$PWD/gitlabs/config:/etc/gitlab'
      - '$PWD/gitlabs/logs:/var/log/gitlab'
      - '$PWD/gitlabs/data:/var/opt/gitlab'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    shm_size: '256m'

  runner:
    image: 'gitlab/gitlab-runner'
    restart: always

    volumes:
      - '$PWD/runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

    



